title: Site

fields:
  title:
    label: Title
    type:  text

  home_image:
    label: Home Image
    type: select
    options: images
    width: 1/2
    help: Add an image to the sidebar, then select it here

  author:
    label: Author
    type:  text
    width: 1/2

  description:
    label: Description
    type:  textarea

  footer:
    label: Footer
    type:  textarea
